@baseUrl = http://127.0.0.1:3000

# =====================
# AUTH
# =====================

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{user1}}",
  "password": "123456"
}

> {%
  client.global.set("authToken", response.body.accessToken)
  client.global.set("refreshToken", response.body.refreshToken)
%}

### Refresh Token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
  client.global.set("authToken", response.body.accessToken)
%}

###

# =====================
# USERS
# =====================

### Criar primeiro usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "user1_{{$timestamp}}@teste.com",
  "password": "123456",
  "name": "Novo Usuário 1"
}

> {%
  client.global.set("userId", response.body.id)
  client.global.set("user1", response.body.email)
%}

### Criar segundo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "user2_{{$timestamp}}@teste.com",
  "password": "123456",
  "name": "Novo Usuário 2"
}

> {%
  client.global.set("secondUserId", response.body.id)
  client.global.set("user2", response.body.email)
%}

### Listar todos os usuários (paginação)
GET {{baseUrl}}/users?limit=10&offset=0
Authorization: Bearer {{authToken}}

### Buscar usuário criado
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}

### Atualizar usuário criado
PATCH {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Name Atualizado"
}

### Deletar usuário criado
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}

# =====================
# MESSAGES
# =====================

### Criar mensagem para o segundo usuário
POST {{baseUrl}}/messages
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "text": "{{$timestamp}} Este texto deve chegar no e-mail",
  "toId": "{{secondUserId}}"
}

> {%
  client.global.set("messageId", response.body.id)
%}

### Listar todas as mensagens (paginação)
GET {{baseUrl}}/messages?limit=10&offset=0
Authorization: Bearer {{authToken}}

### Buscar mensagem criada
GET {{baseUrl}}/messages/{{messageId}}
Authorization: Bearer {{authToken}}

### Atualizar mensagem criada
PATCH {{baseUrl}}/messages/{{messageId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "text": "De Rodrigo para o usuário criado {{$timestamp}}",
  "isRead": true
}

### Deletar mensagem criada
DELETE {{baseUrl}}/messages/{{messageId}}
Authorization: Bearer {{authToken}}

# =====================
# UPLOAD
# =====================

### Upload de foto do usuário criado
POST {{baseUrl}}/users/upload-picture
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data

--file
Content-Disposition: form-data; name="file"; filename="man.png"
Content-Type: image/png

< ./dev/images/man.png

### Visualizar foto do usuário criado
GET {{baseUrl}}/pictures/{{userId}}.jpg
Authorization: Bearer {{authToken}}
